In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV  # Hyperparameyer tuning

from sklearn.preprocessing import MinMaxScaler, StandardScaler  #Feature Scaling

from sklearn.neighbors import KNeighborsClassifier

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [2]:
df=pd.read_csv('car_evaluation[1].csv')
df

buying  maint  doors persons lug_boot safety class\t
0     vhigh  vhigh      2       2    small    low   unacc
1     vhigh  vhigh      2       2    small    med   unacc
2     vhigh  vhigh      2       2    small   high   unacc
3     vhigh  vhigh      2       2      med    low   unacc
4     vhigh  vhigh      2       2      med    med   unacc
...     ...    ...    ...     ...      ...    ...     ...
1723    low    low  5more    more      med    med    good
1724    low    low  5more    more      med   high   vgood
1725    low    low  5more    more      big    low   unacc
1726    low    low  5more    more      big    med    good
1727    low    low  5more    more      big   high   vgood

[1728 rows x 7 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   buying    1728 non-null   object
 1   maint     1728 non-null   object
 2   doors     1728 non-null   object
 3   persons   1728 non-null   object
 4   lug_boot  1728 non-null   object
 5   safety    1728 non-null   object
 6   class	    1728 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB


In [4]:
df['buying'].unique(),df['maint'].unique(),df['doors'].unique(),df['persons'].unique(),df['lug_boot'].unique(),df['safety'].unique()

(array(['vhigh', 'high', 'med', 'low'], dtype=object),
 array(['vhigh', 'high', 'med', 'low'], dtype=object),
 array(['2', '3', '4', '5more'], dtype=object),
 array(['2', '4', 'more'], dtype=object),
 array(['small', 'med', 'big'], dtype=object),
 array(['low', 'med', 'high'], dtype=object))

In [5]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['buying'] = label_encoder.fit_transform(df['buying'])
df['maint']=label_encoder.fit_transform(df['maint'])
df['lug_boot']=label_encoder.fit_transform(df['lug_boot'])
df['safety']=label_encoder.fit_transform(df['safety'])
df

buying  maint  doors persons  lug_boot  safety class\t
0          3      3      2       2         2       1   unacc
1          3      3      2       2         2       2   unacc
2          3      3      2       2         2       0   unacc
3          3      3      2       2         1       1   unacc
4          3      3      2       2         1       2   unacc
...      ...    ...    ...     ...       ...     ...     ...
1723       1      1  5more    more         1       2    good
1724       1      1  5more    more         1       0   vgood
1725       1      1  5more    more         0       1   unacc
1726       1      1  5more    more         0       2    good
1727       1      1  5more    more         0       0   vgood

[1728 rows x 7 columns]

In [6]:
df['class\t'].unique()

array(['unacc', 'acc', 'vgood', 'good'], dtype=object)

In [7]:
# df['class\t'] = df['class\t'].replace({'unaccacc': 0, 'vgood': 2, 'good': 1})


In [8]:
df.loc[df['class\t'] == 'unacc', 'class\t'] = 0
df.loc[df['class\t'] == 'vgood', 'class\t'] = 2
df.loc[df['class\t'] == 'good', 'class\t'] = 1
df.loc[df['class\t'] == 'acc', 'class\t'] = 1

In [9]:
df

buying  maint  doors persons  lug_boot  safety class\t
0          3      3      2       2         2       1       0
1          3      3      2       2         2       2       0
2          3      3      2       2         2       0       0
3          3      3      2       2         1       1       0
4          3      3      2       2         1       2       0
...      ...    ...    ...     ...       ...     ...     ...
1723       1      1  5more    more         1       2       1
1724       1      1  5more    more         1       0       2
1725       1      1  5more    more         0       1       0
1726       1      1  5more    more         0       2       1
1727       1      1  5more    more         0       0       2

[1728 rows x 7 columns]

In [10]:
df['doors'].replace('5more',5,inplace=True)

C:\Users\mvara\AppData\Local\Temp\ipykernel_8764\3153385744.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['doors'].replace('5more',5,inplace=True)


In [11]:
df['doors'].unique()

array(['2', '3', '4', 5], dtype=object)

In [12]:
df

buying  maint doors persons  lug_boot  safety class\t
0          3      3     2       2         2       1       0
1          3      3     2       2         2       2       0
2          3      3     2       2         2       0       0
3          3      3     2       2         1       1       0
4          3      3     2       2         1       2       0
...      ...    ...   ...     ...       ...     ...     ...
1723       1      1     5    more         1       2       1
1724       1      1     5    more         1       0       2
1725       1      1     5    more         0       1       0
1726       1      1     5    more         0       2       1
1727       1      1     5    more         0       0       2

[1728 rows x 7 columns]

In [13]:
df['persons'].replace('more',6,inplace=True)

C:\Users\mvara\AppData\Local\Temp\ipykernel_8764\405281658.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['persons'].replace('more',6,inplace=True)


In [14]:
df

buying  maint doors persons  lug_boot  safety class\t
0          3      3     2       2         2       1       0
1          3      3     2       2         2       2       0
2          3      3     2       2         2       0       0
3          3      3     2       2         1       1       0
4          3      3     2       2         1       2       0
...      ...    ...   ...     ...       ...     ...     ...
1723       1      1     5       6         1       2       1
1724       1      1     5       6         1       0       2
1725       1      1     5       6         0       1       0
1726       1      1     5       6         0       2       1
1727       1      1     5       6         0       0       2

[1728 rows x 7 columns]

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   buying    1728 non-null   int32 
 1   maint     1728 non-null   int32 
 2   doors     1728 non-null   object
 3   persons   1728 non-null   object
 4   lug_boot  1728 non-null   int32 
 5   safety    1728 non-null   int32 
 6   class	    1728 non-null   object
dtypes: int32(4), object(3)
memory usage: 67.6+ KB


In [16]:
df['doors'] = df['doors'].astype(int)
df['persons'] = df['persons'].astype(int)
df['class\t'] = df['class\t'].astype(int)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   buying    1728 non-null   int32
 1   maint     1728 non-null   int32
 2   doors     1728 non-null   int32
 3   persons   1728 non-null   int32
 4   lug_boot  1728 non-null   int32
 5   safety    1728 non-null   int32
 6   class	    1728 non-null   int32
dtypes: int32(7)
memory usage: 47.4 KB


In [18]:
x=df.iloc[:,:-1]
x

buying  maint  doors  persons  lug_boot  safety
0          3      3      2        2         2       1
1          3      3      2        2         2       2
2          3      3      2        2         2       0
3          3      3      2        2         1       1
4          3      3      2        2         1       2
...      ...    ...    ...      ...       ...     ...
1723       1      1      5        6         1       2
1724       1      1      5        6         1       0
1725       1      1      5        6         0       1
1726       1      1      5        6         0       2
1727       1      1      5        6         0       0

[1728 rows x 6 columns]

In [19]:
y=df['class\t']
y

0       0
1       0
2       0
3       0
4       0
       ..
1723    1
1724    2
1725    0
1726    1
1727    2
Name: class\t, Length: 1728, dtype: int32

In [20]:
X_train, X_test, y_train, y_test = train_test_split(x, y,test_size=0.20, random_state=42)

In [21]:
X_train

buying  maint  doors  persons  lug_boot  safety
107        3      3      5        6         0       0
901        2      3      3        4         2       2
1709       1      1      5        2         0       0
706        0      2      4        2         1       2
678        0      2      3        2         1       1
...      ...    ...    ...      ...       ...     ...
1130       2      2      3        6         1       0
1294       2      1      5        6         0       2
860        0      1      5        6         1       0
1459       1      0      4        2         2       2
1126       2      2      3        6         2       2

[1382 rows x 6 columns]

In [22]:
# Normalize features (optional but recommended)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Convert back to DataFrame with column names
X_train = pd.DataFrame(X_train_scaled, columns=X_train.columns)
X_test = pd.DataFrame(X_test_scaled, columns=X_test.columns)


In [23]:
X_test

buying     maint     doors   persons  lug_boot    safety
0   -1.351852 -1.326248  0.449025 -1.241095 -0.001770 -1.232997
1    0.450617 -0.434338 -1.336737 -0.008030 -0.001770  1.227655
2   -1.351852 -1.326248  1.341906 -1.241095 -1.224748  1.227655
3   -0.450617 -1.326248  1.341906 -0.008030 -0.001770  1.227655
4    0.450617 -0.434338  0.449025  1.225035 -0.001770 -0.002671
..        ...       ...       ...       ...       ...       ...
341  1.351852  1.349481  1.341906  1.225035  1.221208  1.227655
342  1.351852  0.457572  0.449025 -1.241095 -0.001770  1.227655
343  0.450617 -0.434338 -1.336737  1.225035  1.221208 -0.002671
344  1.351852  1.349481  1.341906  1.225035  1.221208 -1.232997
345  0.450617  0.457572 -1.336737 -1.241095 -0.001770  1.227655

[346 rows x 6 columns]

In [24]:
knn_class = KNeighborsClassifier(n_neighbors=1, p=2)
knn_class.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [46]:
y_pred = knn_class.predict(X_test)
y_pred

array([0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 2, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 2, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 2, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 2, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 2, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       2, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,

In [47]:
y_test

599     0
1201    1
628     0
1498    1
1263    0
       ..
100     0
274     0
1206    0
101     0
1084    0
Name: class\t, Length: 346, dtype: int32

In [48]:
y.value_counts()

class\t
0    1210
1     453
2      65
Name: count, dtype: int64

In [49]:
con_matrix = confusion_matrix(y_test, y_pred)
con_matrix

array([[209,  26,   0],
       [ 23,  67,   4],
       [  0,  11,   6]], dtype=int64)

In [50]:
accuracy= accuracy_score(y_test, y_pred)
accuracy

0.815028901734104

In [51]:
class_report = classification_report(y_test, y_pred)
print(class_report)

              precision    recall  f1-score   support

           0       0.90      0.89      0.90       235
           1       0.64      0.71      0.68        94
           2       0.60      0.35      0.44        17

    accuracy                           0.82       346
   macro avg       0.72      0.65      0.67       346
weighted avg       0.82      0.82      0.81       346



to evalute using gidsearch cv

In [65]:
k = np.arange(2,15)
p = [1,2]
hyp = {'n_neighbors': k, "p":p}

In [66]:
knn = KNeighborsClassifier()
gscv_knn_model = GridSearchCV(knn,hyp,cv=5)
gscv_knn_model.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
                         'p': [1, 2]})

In [67]:
gscv_knn_model.best_params_

{'n_neighbors': 12, 'p': 1}

In [68]:
y_pred1 = knn_class.predict(X_test)
y_pred1

array([0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 2, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 2, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 2, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 2, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 2, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       2, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,

In [69]:
accuracy_gs= accuracy_score(y_test, y_pred1)
accuracy_gs*100

81.5028901734104

Same as randomizedsearchcv

In [58]:
knn = KNeighborsClassifier()
rscv_knn_model = RandomizedSearchCV(knn,hyp,cv=5)
rscv_knn_model.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(),
                   param_distributions={'n_neighbors': array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
                                        'p': [1, 2]})

In [59]:
rscv_knn_model.best_params_

{'p': 1, 'n_neighbors': 9}

In [71]:
knn_class_gs = KNeighborsClassifier(n_neighbors=9, p=2)
knn_class_gs.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=9)

In [72]:
y_pred2 = knn_class_gs.predict(X_test)
y_pred2

array([0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 2,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 2, 0, 0, 0, 2, 1, 0, 1,
       1, 2, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 2, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 2, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       2, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 2, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 2, 1, 1, 0, 0, 0, 0, 2, 1, 1, 0, 0, 0,

In [73]:
con_matrix = confusion_matrix(y_test, y_pred_gs)
con_matrix

array([[225,  10,   0],
       [  9,  84,   1],
       [  0,   6,  11]], dtype=int64)

In [74]:
class_report = classification_report(y_test, y_pred_gs)
print(class_report)

              precision    recall  f1-score   support

           0       0.96      0.96      0.96       235
           1       0.84      0.89      0.87        94
           2       0.92      0.65      0.76        17

    accuracy                           0.92       346
   macro avg       0.91      0.83      0.86       346
weighted avg       0.93      0.92      0.92       346



In [76]:
accuracy_gs= accuracy_score(y_test, y_pred_gs)
accuracy_gs*100

92.48554913294798

## YES we get best accuracy using randomaziedsearchcv hyperparameter optimization technique that is 92.48%

In [77]:
knn_class_gs.predict([[3,3,5,6,0,0]])

C:\Users\mvara\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([0])

In [44]:
y_train

107     0
901     0
1709    0
706     0
678     0
       ..
1130    2
1294    1
860     1
1459    0
1126    1
Name: class\t, Length: 1382, dtype: int32

In [45]:
df

buying  maint  doors  persons  lug_boot  safety  class\t
0          3      3      2        2         2       1        0
1          3      3      2        2         2       2        0
2          3      3      2        2         2       0        0
3          3      3      2        2         1       1        0
4          3      3      2        2         1       2        0
...      ...    ...    ...      ...       ...     ...      ...
1723       1      1      5        6         1       2        1
1724       1      1      5        6         1       0        2
1725       1      1      5        6         0       1        0
1726       1      1      5        6         0       2        1
1727       1      1      5        6         0       0        2

[1728 rows x 7 columns]